feat: multiple page directories and custom route names/paths
hannoeru/vite-plugin-pages pull request #10
Opened 2021-02-09 01:21 UTC by JohnCampionJr

Closes #8

First round; let me know what you think.  Need to add doc to README.

Appreciate your insight and tweaks; especially around naming things.

2021-02-09 07:38 UTC, hannoeru commented on src/index.ts
> +          options.pagesDirPaths = []
I think you can move this one to plugin root function, don't need to be a resolved options.

2021-02-10 23:52 UTC, JohnCampionJr commented
All set :)

2021-02-11 15:54 UTC, hannoeru requested changes

2021-02-11 15:54 UTC, hannoeru commented on src/generate.ts
> +        route.path = `/${pagesDirOptions.baseRoute}${route.path}`
```suggestion
        const baseRoute = `/${pagesDirOptions.baseRoute}`
        route.path === '/' ? baseRoute : baseRoute + route.path
```

Prevent something end with `/` in route path.

2021-02-11 15:59 UTC, merged