Remove inlining import statements for async importmode
hannoeru/vite-plugin-pages pull request #187
Opened 2022-03-18 11:58 UTC by shkreios

# Current behavior
Async imports are handled inline
# New behavior
Async imports are handled the same way as sync imports

# Advantages
- Clean stringify code => no special cases
- Option in the future to allow preloaded

2022-03-18 19:58 UTC, hannoeru requested changes
Looks great, but can you revert all coding style changes that cause by prettier? I personally don't use prettier.

2022-03-19 14:04 UTC, shkreios commented
> Looks great, but can you revert all coding style changes that cause by prettier? I personally don't use prettier.

I tried to configure prettier to look as similar as possible to your codestyle. Which styling tool are you using so I can easily revert the changes?

Thanks

2022-03-19 14:08 UTC, hannoeru commented on src/stringify.ts
> -    .stringify(preparedRoutes, replaceFunction)
revert this

2022-03-19 14:11 UTC, hannoeru commented
Only ESLint, I don't want to have any coding style changes on the existing code in this PR.

2022-03-19 14:47 UTC, shkreios commented
Ah sorry I thought you maybe had some tool, so contributors could easliy conform to the existing coding style.

2022-03-19 16:47 UTC, hannoeru commented
Just add a vscode settings to disable prettier in this repo, thanks for revert those changes.

2022-03-19 16:47 UTC, hannoeru approved these changes

2022-03-19 16:49 UTC, merged